name: CI test app

on: [ pull_request ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Compose dependence
        run: docker compose build

  test:

    runs-on: ubuntu-latest

    needs: build

    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install --workspaces
      - name: Test
        run: npm test --workspaces --if-present

  merge:
    runs-on: ubuntu-latest

    needs: test

    steps:
      - uses: actions/checkout@master

      - name: Merge actions -> main
        uses: devmasx/merge-branch@master
        with:
          type: now
          target_branch: main
          github_token: ${{ github.token }}
