version: '2'

services:
    proxy:
        image: nginx
        container_name: proxy
        depends_on:
            - front
            - back
            - docs
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
        ports:
            - "5012:5012"
    front:
        build:
            context: ./front
        container_name: front
        expose:
            - "8080"
    docs:
        build:
            context: ./docs
        container_name: docs
        expose:
            - "8085"
    db:
        image: postgres
        container_name: db
        ports:
            - "5432"
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=postgres
        volumes:
            - ./db/init.sh:/docker-entrypoint-initdb.d/init.sh
    back:
        build:
            context: ./back
        container_name: back
        depends_on:
            - db
        restart: on-failure
        volumes:
            - type: bind
              source: ./back/src
              target: /src
        expose:
            - "8082"
